version: '3.8'

services:
  cms:
    build:
      context: .
      dockerfile: Dockerfile.static
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - cms-network

  # Development service
  cms-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - cms-network
    profiles:
      - dev

  # Serve already-built ./out via Apache without building inside Docker
  cms-static-mount:
    image: httpd:2.4-alpine
    ports:
      - "3000:80"
    volumes:
      - ./out:/usr/local/apache2/htdocs:ro
      - ./apache.conf:/usr/local/apache2/conf/httpd.conf:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - cms-network
    profiles:
      - static-mount

networks:
  cms-network:
    driver: bridge 